# Generated by Django 5.0.6 on 2024-08-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_product_category_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additem',
            old_name='recipe',
            new_name='product',
        ),
    ]
