# Generated by Django 5.0.6 on 2024-08-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_rename_recipe_additem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
