# Generated by Django 5.0.6 on 2024-08-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_category_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
