# Generated by Django 5.0.6 on 2024-08-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_goods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
