# Generated by Django 5.0.6 on 2024-08-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.product'),
        ),
    ]
