# Generated by Django 5.0.6 on 2024-08-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0024_alter_orderdetail_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_name',
            field=models.CharField(max_length=250),
        ),
    ]
