# Generated by Django 5.0.6 on 2024-08-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_alter_orderdetail_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
