# Generated by Django 5.0.6 on 2024-08-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_alter_orderdetail_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_name',
            new_name='name',
        ),
    ]
