# Generated by Django 5.0.6 on 2024-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_rename_product_name_orderdetail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='name',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_name',
            field=models.CharField(default=1, max_length=250),
        ),
    ]
